package com.ocean.pojo;

import java.util.Date;

public class CszpAddressManage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cszp_address_manage.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cszp_address_manage.send_company
     *
     * @mbggenerated
     */
    private String sendCompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cszp_address_manage.send_person
     *
     * @mbggenerated
     */
    private String sendPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cszp_address_manage.send_mobile
     *
     * @mbggenerated
     */
    private String sendMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cszp_address_manage.send_province
     *
     * @mbggenerated
     */
    private String sendProvince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cszp_address_manage.send_province_code
     *
     * @mbggenerated
     */
    private String sendProvinceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cszp_address_manage.send_city
     *
     * @mbggenerated
     */
    private String sendCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cszp_address_manage.send_city_code
     *
     * @mbggenerated
     */
    private String sendCityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cszp_address_manage.send_district
     *
     * @mbggenerated
     */
    private String sendDistrict;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cszp_address_manage.send_district_code
     *
     * @mbggenerated
     */
    private String sendDistrictCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cszp_address_manage.send_address
     *
     * @mbggenerated
     */
    private String sendAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cszp_address_manage.is_default_address
     *
     * @mbggenerated
     */
    private Boolean isDefaultAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cszp_address_manage.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cszp_address_manage.status
     *
     * @mbggenerated
     */
    private Boolean status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cszp_address_manage.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cszp_address_manage.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cszp_address_manage.create_by
     *
     * @mbggenerated
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cszp_address_manage.update_by
     *
     * @mbggenerated
     */
    private String updateBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cszp_address_manage.id
     *
     * @return the value of cszp_address_manage.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cszp_address_manage.id
     *
     * @param id the value for cszp_address_manage.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cszp_address_manage.send_company
     *
     * @return the value of cszp_address_manage.send_company
     *
     * @mbggenerated
     */
    public String getSendCompany() {
        return sendCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cszp_address_manage.send_company
     *
     * @param sendCompany the value for cszp_address_manage.send_company
     *
     * @mbggenerated
     */
    public void setSendCompany(String sendCompany) {
        this.sendCompany = sendCompany == null ? null : sendCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cszp_address_manage.send_person
     *
     * @return the value of cszp_address_manage.send_person
     *
     * @mbggenerated
     */
    public String getSendPerson() {
        return sendPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cszp_address_manage.send_person
     *
     * @param sendPerson the value for cszp_address_manage.send_person
     *
     * @mbggenerated
     */
    public void setSendPerson(String sendPerson) {
        this.sendPerson = sendPerson == null ? null : sendPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cszp_address_manage.send_mobile
     *
     * @return the value of cszp_address_manage.send_mobile
     *
     * @mbggenerated
     */
    public String getSendMobile() {
        return sendMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cszp_address_manage.send_mobile
     *
     * @param sendMobile the value for cszp_address_manage.send_mobile
     *
     * @mbggenerated
     */
    public void setSendMobile(String sendMobile) {
        this.sendMobile = sendMobile == null ? null : sendMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cszp_address_manage.send_province
     *
     * @return the value of cszp_address_manage.send_province
     *
     * @mbggenerated
     */
    public String getSendProvince() {
        return sendProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cszp_address_manage.send_province
     *
     * @param sendProvince the value for cszp_address_manage.send_province
     *
     * @mbggenerated
     */
    public void setSendProvince(String sendProvince) {
        this.sendProvince = sendProvince == null ? null : sendProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cszp_address_manage.send_province_code
     *
     * @return the value of cszp_address_manage.send_province_code
     *
     * @mbggenerated
     */
    public String getSendProvinceCode() {
        return sendProvinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cszp_address_manage.send_province_code
     *
     * @param sendProvinceCode the value for cszp_address_manage.send_province_code
     *
     * @mbggenerated
     */
    public void setSendProvinceCode(String sendProvinceCode) {
        this.sendProvinceCode = sendProvinceCode == null ? null : sendProvinceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cszp_address_manage.send_city
     *
     * @return the value of cszp_address_manage.send_city
     *
     * @mbggenerated
     */
    public String getSendCity() {
        return sendCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cszp_address_manage.send_city
     *
     * @param sendCity the value for cszp_address_manage.send_city
     *
     * @mbggenerated
     */
    public void setSendCity(String sendCity) {
        this.sendCity = sendCity == null ? null : sendCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cszp_address_manage.send_city_code
     *
     * @return the value of cszp_address_manage.send_city_code
     *
     * @mbggenerated
     */
    public String getSendCityCode() {
        return sendCityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cszp_address_manage.send_city_code
     *
     * @param sendCityCode the value for cszp_address_manage.send_city_code
     *
     * @mbggenerated
     */
    public void setSendCityCode(String sendCityCode) {
        this.sendCityCode = sendCityCode == null ? null : sendCityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cszp_address_manage.send_district
     *
     * @return the value of cszp_address_manage.send_district
     *
     * @mbggenerated
     */
    public String getSendDistrict() {
        return sendDistrict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cszp_address_manage.send_district
     *
     * @param sendDistrict the value for cszp_address_manage.send_district
     *
     * @mbggenerated
     */
    public void setSendDistrict(String sendDistrict) {
        this.sendDistrict = sendDistrict == null ? null : sendDistrict.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cszp_address_manage.send_district_code
     *
     * @return the value of cszp_address_manage.send_district_code
     *
     * @mbggenerated
     */
    public String getSendDistrictCode() {
        return sendDistrictCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cszp_address_manage.send_district_code
     *
     * @param sendDistrictCode the value for cszp_address_manage.send_district_code
     *
     * @mbggenerated
     */
    public void setSendDistrictCode(String sendDistrictCode) {
        this.sendDistrictCode = sendDistrictCode == null ? null : sendDistrictCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cszp_address_manage.send_address
     *
     * @return the value of cszp_address_manage.send_address
     *
     * @mbggenerated
     */
    public String getSendAddress() {
        return sendAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cszp_address_manage.send_address
     *
     * @param sendAddress the value for cszp_address_manage.send_address
     *
     * @mbggenerated
     */
    public void setSendAddress(String sendAddress) {
        this.sendAddress = sendAddress == null ? null : sendAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cszp_address_manage.is_default_address
     *
     * @return the value of cszp_address_manage.is_default_address
     *
     * @mbggenerated
     */
    public Boolean getIsDefaultAddress() {
        return isDefaultAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cszp_address_manage.is_default_address
     *
     * @param isDefaultAddress the value for cszp_address_manage.is_default_address
     *
     * @mbggenerated
     */
    public void setIsDefaultAddress(Boolean isDefaultAddress) {
        this.isDefaultAddress = isDefaultAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cszp_address_manage.user_id
     *
     * @return the value of cszp_address_manage.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cszp_address_manage.user_id
     *
     * @param userId the value for cszp_address_manage.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cszp_address_manage.status
     *
     * @return the value of cszp_address_manage.status
     *
     * @mbggenerated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cszp_address_manage.status
     *
     * @param status the value for cszp_address_manage.status
     *
     * @mbggenerated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cszp_address_manage.create_time
     *
     * @return the value of cszp_address_manage.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cszp_address_manage.create_time
     *
     * @param createTime the value for cszp_address_manage.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cszp_address_manage.update_time
     *
     * @return the value of cszp_address_manage.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cszp_address_manage.update_time
     *
     * @param updateTime the value for cszp_address_manage.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cszp_address_manage.create_by
     *
     * @return the value of cszp_address_manage.create_by
     *
     * @mbggenerated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cszp_address_manage.create_by
     *
     * @param createBy the value for cszp_address_manage.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cszp_address_manage.update_by
     *
     * @return the value of cszp_address_manage.update_by
     *
     * @mbggenerated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cszp_address_manage.update_by
     *
     * @param updateBy the value for cszp_address_manage.update_by
     *
     * @mbggenerated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }
}